<?php

namespace Phantom\Console\Commands;

use Phantom\Core\Container;
use Exception;
use ReflectionMethod;
use ReflectionFunction;

class ApiDocCommand
{
    public $signature = 'api:doc';
    public $description = 'Generate OpenAPI documentation using AI analysis';

    public function handle($args = [])
    {
        echo "🔍 Scanning routes and analyzing controllers...
";

        $router = Container::getInstance()->make('router');
        $routes = $router->getRoutes();
        $openApi = [
            'openapi' => '3.0.0',
            'info' => [
                'title' => config('app.name') . ' API',
                'version' => '1.0.0',
                'description' => 'Automatically generated by Phantom AI'
            ],
            'servers' => [
                ['url' => config('app.url'), 'description' => 'Current Environment']
            ],
            'components' => [
                'securitySchemes' => [
                    'csrf' => [
                        'type' => 'apiKey',
                        'in' => 'header',
                        'name' => 'X-CSRF-TOKEN'
                    ]
                ]
            ],
            'paths' => []
        ];

        foreach ($routes as $route) {
            // Skip framework internal routes
            if (str_contains($route['uri'], '/phantom/')) continue;

            echo "  - Analyzing [{$route['method']}] {$route['uri']}...
";

            $context = $this->getActionContext($route['action']);
            
            try {
                $spec = $this->analyzeWithAi($route, $context);
                
                $uri = $route['uri'];
                $method = strtolower($route['method']);
                
                if (!isset($openApi['paths'][$uri])) {
                    $openApi['paths'][$uri] = [];
                }

                $openApi['paths'][$uri][$method] = $spec;

            } catch (Exception $e) {
                echo "    ⚠️ Failed: " . $e->getMessage() . "
";
            }
        }

        $json = json_encode($openApi, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        file_put_contents(base_path('public/swagger.json'), $json);

        echo "
✅ Documentation generated: public/swagger.json
";
        echo "💡 Tip: You can load this file into any Swagger UI or Postman.
";
    }

    protected function getActionContext($action)
    {
        if (is_array($action)) {
            [$class, $method] = $action;
            $reflection = new ReflectionMethod($class, $method);
            $fileName = $reflection->getFileName();
            $startLine = $reflection->getStartLine() - 1;
            $endLine = $reflection->getEndLine();
            $length = $endLine - $startLine;

            $lines = file($fileName);
            return implode('', array_slice($lines, $startLine, $length));
        }

        if ($action instanceof \Closure) {
            $reflection = new ReflectionFunction($action);
            return "Closure at " . $reflection->getFileName() . " line " . $reflection->getStartLine();
        }

        return "Unknown action type";
    }

    protected function analyzeWithAi($route, $code)
    {
        $prompt = "You are an OpenAPI expert. Analyze the following PHP code for a Phantom Framework route and return ONLY a valid JSON fragment for the 'operation' object in OpenAPI 3.0 spec.
        
        Route: [{$route['method']}] {$route['uri']}
        Code:
        {$code}
        
        Rules:
        1. Include 'summary', 'description', 'parameters' (if any in URI), and 'responses' (200, 400, etc).
        2. Do not include markdown blocks. Return only the JSON object.
        3. If you see validation rules like \$request->validate(), include them in the description or parameters.
        ";

        $response = ai()->generate($prompt);
        
        // Clean response
        $response = preg_replace('/^```json\s*/', '', $response);
        $response = preg_replace('/\s*```$/', '', $response);
        $response = trim($response);

        $data = json_decode($response, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new Exception("AI returned invalid JSON: " . substr($response, 0, 50) . "...");
        }

        return $data;
    }
}
